# Generated by Django 4.0.2 on 2022-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_users_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
