# Generated by Django 4.0.2 on 2022-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='cash',
            field=models.FloatField(),
        ),
    ]
