# Generated by Django 4.0.3 on 2022-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_transactions_price_alter_users_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
