# Generated by Django 4.0.3 on 2022-04-03 04:48

from django.db import migrations
import practice.models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=practice.models.DateTimeWithoutTZField(auto_now=True),
        ),
    ]
