# Generated by Django 4.0.2 on 2022-04-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.DateTimeField(default='24/04/2022 22:14:23'),
        ),
    ]
