# Generated by Django 4.0.3 on 2022-04-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
