# Generated by Django 4.0.2 on 2022-04-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_alter_transactions_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='time',
            field=models.DateTimeField(default='2022-04-24 22:18:54'),
        ),
    ]
